using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BEL
{
    public enum Permisos
    {
        Backup_Realizar = 1,
        Backup_Restaurar = 2,
        Backup_Consultar = 3,
        Permisos_Alta = 4,
        Permisos_Baja = 5,
        Permiso_Modificar = 6,
        Permiso_Consultar = 7,
        Integridad_Consultar = 8,
        Integridad_Reparar = 9,
        Logs_Consultar = 10,
        Usuario_Alta = 11,
        Usuario_Baja = 12,
        Usuario_Modificar = 13,
        Usuario_Consultar = 14,
        Idioma_Alta = 15,
        Idioma_Baja = 16,
        Idioma_Modificar = 17,
        Idioma_Consultar = 18,
        Activo_Alta = 20,
        Activo_Baja = 21,
        Activo_Modificar = 22,
        Activo_Consultar = 23,
        Cliente_Alta = 25,
        Cliente_Baja = 26,
        Cliente_Modificar = 27,
        Cliente_Consultar = 28,
        Deposito_Alta = 29,
        Deposito_Baja = 30,
        Deposito_Modificar = 31,
        Deposito_Consultar = 32,
        Reparacion_Alta = 33,
        Reparacion_Baja = 34,
        Reparacion_Modificar = 35,
        Reparacion_Consultar = 36,
        Donacion_Alta = 37,
        Donacion_Baja = 38,
        Donacion_Modificar = 39,
        Donacion_Consultar = 40,
        Gestionar_Activos = 41,
        Propiedades_Activos = 42,
        Gestionar_PCs = 43,
        Categorias_PCs = 44,
        Propuesta_Reemplazo = 45,
        Usuario_de_Activos = 46,
        Gestionar_Depositos = 47,
        Gestionar_Donacion = 48,
        Propuesta_Donacion = 49,
        Gestionar_Reparacion = 50,
        Gestionar_Proveedores = 51,
        Gestionar_Recurrentes = 52,
        Gestionar_Ubicaciones = 53,
        Reparacion_Ingreso_Facturas = 55,
        Reparacion_Ordenes_Pago = 56,
    }
}
